"""Generate an Icarus-compatible copy of cart_reader.v for simulation.

cart_reader.v as vendored (and as synthesised) uses two constructs Icarus
rejects outright, so the file cannot be simulated as-is:

  1. `break` inside a for loop
  2. a variable index into a packed union as an lvalue,
     flash_commands.as_bytes[blob_idx] <= rx_data

The obvious move is to rewrite those in the real file. That was tried and it is
the wrong trade: the union is not just documentation, it tells the synthesiser
both the element bound and the lane alignment. Three hand-rolled flattenings
were measured, and every one blew past the device limit -

    descending arithmetic, raw indices     28318 LUTs
    descending arithmetic, bounded indices 29514 LUTs
    ascending, simple-multiply bases       27842 LUTs
    the packed union                       17367 LUTs   (limit 23040)

So the synthesised file keeps the union, and simulation gets a transformed copy
instead. The transforms are confined to the flash-command bookkeeping, which is
unrelated to the rx/command-parsing path the bench exercises.

Usage:  python mksim.py        -> writes cart_reader_sim.v beside this script
"""
import io, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC  = os.path.join(HERE, "..", "..", "src", "rtl", "cart_reader.v")
DST  = os.path.join(HERE, "cart_reader_sim.v")

s = io.open(SRC, encoding="utf8").read()
subs = 0

# 1. break -> descending scan. Every match assigns and the assignment is
#    nonblocking, so the last executed wins; descending, that is the LOWEST
#    matching index - exactly what the ascending loop with `break` produced.
old_break = """            for (integer i = 0; i < FLASH_COMMANDS_MAX; i = i + 1) begin
                if (flash_commands.as_struct[i].address == 16'h0000 && flash_commands.as_struct[i].data == 16'h0000) begin
                    flash_command_count <= i;
                    break;
                end
            end"""
new_break = """            for (integer i = FLASH_COMMANDS_MAX - 1; i >= 0; i = i - 1) begin
                if (flash_commands.as_struct[i].address == 16'h0000 && flash_commands.as_struct[i].data == 16'h0000) begin
                    flash_command_count <= i;
                end
            end"""
if old_break in s:
    s = s.replace(old_break, new_break); subs += 1

# 2. packed union -> flat vector. Layout is preserved exactly: flash_command_t
#    is {unused_addr_msb[15:0], address[15:0], unused_data_msb[7:0], data[7:0]}
#    = 48 bits, and BOTH union views were declared ascending ([0:N-1]), so
#    index 0 is the most significant element/byte. Declaring the replacement
#    ascending keeps every base a plain multiple of the element size.
old_union = """union packed {
  flash_command_t [0:FLASH_COMMANDS_MAX - 1] as_struct;
  logic [0:(FLASH_COMMANDS_MAX * ($bits(flash_command_t) / 8)) - 1][7:0] as_bytes;
} flash_commands;"""
new_union = """localparam FC_BITS  = 48;                           // $bits(flash_command_t)
localparam FC_TOTAL = FLASH_COMMANDS_MAX * FC_BITS; // 288
reg [0:FC_TOTAL-1] flash_commands;"""
if old_union in s:
    s = s.replace(old_union, new_union); subs += 1

repl = [
    ("flash_commands.as_bytes[blob_idx]",
     "flash_commands[8*blob_idx[5:0] +: 8]"),
    ("($bits(flash_commands.as_bytes) / 8)",
     "(FC_TOTAL/8)"),
    ("flash_commands.as_struct[i].address",
     "flash_commands[FC_BITS*i + 16 +: 16]"),
    ("flash_commands.as_struct[i].data",
     "flash_commands[FC_BITS*i + 40 +: 8]"),
    ("flash_commands.as_struct[flash_command_count].address",
     "flash_commands[FC_BITS*flash_command_count[2:0] + 16 +: 16]"),
    ("flash_commands.as_struct[flash_command_count].data",
     "flash_commands[FC_BITS*flash_command_count[2:0] + 40 +: 8]"),
    ("flash_commands.as_struct[par_idx].address",
     "flash_commands[FC_BITS*par_idx[2:0] + 16 +: 16]"),
    ("flash_commands.as_struct[par_idx].data",
     "flash_commands[FC_BITS*par_idx[2:0] + 40 +: 8]"),
]
# longest first, so .as_struct[flash_command_count].address is not clipped by a
# shorter pattern that happens to be a prefix
for a, b in sorted(repl, key=lambda t: -len(t[0])):
    if a in s:
        s = s.replace(a, b); subs += 1

left = s.count("flash_commands.as_") + len(re.findall(r"\bbreak\s*;", s))
if left:
    sys.exit("mksim: %d unconverted construct(s) remain - cart_reader.v has "
             "changed and this script needs updating" % left)

hdr = ("// GENERATED by mksim.py from src/rtl/cart_reader.v - DO NOT EDIT.\n"
       "// Icarus-compatible copy; see mksim.py for what is transformed and why.\n\n")
io.open(DST, "w", encoding="utf8", newline="\n").write(hdr + s)
print("wrote %s (%d transforms)" % (os.path.relpath(DST, HERE), subs))
